developments:
  epochs: 150
  batch_size: 128
  lr_initial: 0.1
model:
  name: klue/bert-base
dataset:
  post_training:
    training:
      name: empty
      path: datasets/lm_post_training/training/LabeledData
      struct: named_entity/#/content/#/sentence
    validation:
      name: empty
      path: datasets/lm_post_training/validation/LabeledData
      struct : named_entity/#/content/#/sentence
    test:
      name: empty
      path: datasets/lm_post_training/test/LabeledData
      struct: named_entity/#/content/#/sentence
fine_tuning:
  data_path: 'squad_kor_v1'
  train:
    model_name: 'klue/bert-base'
    upload_path: 'domainBert-finetuned-squad_kor_v1'
  eval:
    model_name: 'Kdogs/klue-finetuned-squad_kor_v1'
    eval_path: 'eval_model'
  metric_type: 'squad'
  max_length: 512
  stride: 128
  n_best: 20
  max_answer_length: 30
  train_batch: 16
  eval_batch: 16
  learning_rate: 0.00005
  epochs: 3
  weight_decay: 0.01
  fp16: False
  push_to_hub: False
  login_token: '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'
  exec: 'eval'
log:
  default:
    format: '%(levelname)s[%(module)s:%(lineno)d]: %(message)s (%(asctime)s)'
    level: DEBUG
  file:
    format: '%(levelname)s[%(module)s]: %(message)s (%(asctime)s) pid:%(process)d pn:%(processName)s tid:%(thread)d tn:%(threadName)s'
    level: WARNING