developments:
  epochs: 150
  batch_size: 128
  lr_initial: 0.1
model:
  name: klue/bert-base
dataset:
  post_training:
    training:
      name: empty
      path: datasets/lm_post_training/training/LabeledData
      struct: named_entity/#/content/#/sentence
    validation:
      name: empty
      path: datasets/lm_post_training/validation/LabeledData
      struct : named_entity/#/content/#/sentence
    test:
      name: empty
      path: datasets/lm_post_training/test/LabeledData
      struct: named_entity/#/content/#/sentence
log:
  formatters:
    default:
      format: '%(levelname)s[%(module)s]: %(message)s (%(asctime)s)'
    test:
      foramt: '%(levelname)s[%(module)s]: %(message)s'
  handlers:
    root:
      class: logging.StreamHandler
      level: DEBUG
      formatter: default
      stream: "ext://sys.stdout"
    file:
      class: logging.FileHandler
      level: WARNING
      formatter: default
      filename: log.txt
    test:
      class: logging.StreamHanlder
      level: DEBUG
      formatter: default
      stream: "ext://sys.stdout"
