developments:
  epochs: 150
  batch_size: 128
  lr_initial: 0.1
model:
  name: bert-base-multilingual-cased
dataset:
  post_training:
    training:
      name: empty
      path: datasets/lm_post_training/training/TL_span_extraction.json
    validation:
      name: empty
      path: datasets/lm_post_training/validation/VL_span_extraction.json