developments:
  epochs: 150
  batch_size: 128
  lr_initial: 0.1
model:
  name: klue/bert-base
dataset:
  post_training:
    training:
      name: empty
      path: datasets/lm_post_training/training/LabeledData
      struct: named_entity/#/content/#/sentence
    validation:
      name: empty
      path: datasets/lm_post_training/validation/LabeledData
      struct : named_entity/#/content/#/sentence
    test:
      name: empty
      path: datasets/lm_post_training/training/LabeledData
      struct: named_entity/#/content/#/sentence
