version: 1
formatters:
  default:
    format: '%(levelname)s[%(module)s:%(lineno)d]: %(message)s (%(asctime)s)'
    datafmt: '%Y-%m-%d %I:%M:%S %p'
  complex:
    format: '%(levelname)s[%(module)s]:%(message)s (%(asctime)s) pid:%(process)d pn:%(processName)s tid:%(thread)d tn:%(threadName)s'
    datafmt: '%Y-%m-%d %I:%M:%S %p'
handlers:
  console:
    class: logging.StreamHandler
    formatter: default
    level: DEBUG
  file-warning:
    class: logging.FileHandler
    mode: a 
    encoding: utf-8
    filename: log.txt
    formatter: complex
    level: WARNING
  file-train:
    class: logging.FileHandler
    mode: a 
    encoding: utf-8
    filename: train.log
    formatter: complex
    level: INFO
root: 
  handlers:
    - console
    - file-warning
  level: WARNING
loggers:
  only_print:
    handlers:
      - console
    level: DEBUG
    propagate: False
  train:
    handlers: 
      - file-train
    level: INFO
    propagate: False
  test:
    handlers:
      - console
    level: DEBUG
    propagate: False